[package]
name = "set-repeat-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2018"
publish = false

[dependencies.set-repeat]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.4"
path = "../../../../../dharitri-wasm-debug"
