[package]
name = "empty-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.empty]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.4"
path = "../../../../dharitri-wasm-debug"
