[package]
name = "forwarder-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.forwarder]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.4"
path = "../../../../../dharitri-wasm-debug"
