[package]
name = "digital-cash-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.digital-cash]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.4"
path = "../../../../dharitri-wasm-debug"
