[package]
name = "factory-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dependencies.order-book-factory]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.4"
path = "../../../../../dharitri-wasm-debug"
