[package]
name = "proxy-test-second-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.proxy-test-second]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.4"
path = "../../../../../dharitri-wasm-debug"
