[package]
name = "ping-pong-moax-meta"
version = "0.0.0"
authors = [ "Bruda Claudiu-Marcel <claudiu725@yahoo.com>",]
edition = "2018"
publish = false

[dependencies.ping-pong-moax]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.4"
path = "../../../../dharitri-wasm-debug"
