[package]
name = "local-dct-and-nft-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.local-dct-and-nft]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.4"
path = "../../../../../dharitri-wasm-debug"
